### ISSUE TITLE
About architectures in paper

### ISSUE THREAD

**Issue by mrgloom** [titu1994/keras-coordconv#10]
Is there any intuition about usage of `CoordConv` layer? in [paper](https://arxiv.org/pdf/1807.03247.pdf) architectures description is not detailed, i.e. should we replace all convolutions in some existing model (for example VGG16) with `CoordConv` layer or just first convolution?

**Comment by titu1994** [comment]
CoordinateChannel adds an input feature/s for the CNN to learn from. It is equivalent to giving a RGBXY "image" as input to the CNN to learn from. 

In doing so, it makes no sense to add additional XY channels to subsequent layers, as they have already learned from and extracted any useful information from that input. Therefore there is no reason at add more CoordinateChannel layers after this first one. 

Think of it this way, you are resizing and concatinating your original RGB image into subsequent layers, so why do so with the coordinate channel information?

All that being said, I see no harm (other than a slight increase in parameters, and increased training time) to add more of these layers to subsequent parts of the network. My guess is that it may not help at all, but that I cannot say with certainty.

**Comment by mrgloom** [comment]
If we should use it just as first layer maybe it will be more efficient to not have a custom layer, but just input RGBXY to ordinary conv2d? i.e. it should be done on batch generator side.
