### ISSUE TITLE
"use_radius" is not implemented in "CoordinateChannel3D"

### ISSUE THREAD

**Issue by DaneshJoy** [titu1994/keras-coordconv#16]
Thanks for sharing your code 👍 
There is a usage of __use_radius__ argument in the __call__ function for __rank=2__:
```           
if self.use_radius:
    rr = K.sqrt(K.square(xx_channels - 0.5) +
    K.square(yy_channels - 0.5))
    outputs = K.concatenate([outputs, rr], axis=-1)
```

Is it possible to use the same action for __rank=3__ ?

There is a definition for this argument in the docstring of the CoordinateChannel3D, which I assume that is copied from the CoordinateChannel2D:
```
use_radius: Boolean flag to determine whether the
            radius coordinate should be added for 2D rank
            inputs or not.
```

**Comment by titu1994** [comment]
Use radius is supported only on 2d coordconv. That doc should be updated.

**Comment by DaneshJoy** [comment]
Thanks, and Good Luck!
