### ISSUE TITLE
[Feature] Supervised Coordinate Regression experiment

### ISSUE THREAD

**Issue by vfdev-5** [titu1994/keras-coordconv#4]
Hi @titu1994 

Just wonder whether you've tried (or trying) to reimplement  Supervised Coordinate Regression task as presented in the paper: from image with single white pixel regress its coordinates (x, y). I'm working on it with PyTorch and paper's network to regress the coordinates does not work at all. So, would be glad to have a feedback from your side with Keras.

Thanks

**Comment by titu1994** [comment]
I am currently not working on it at the moment, however. As far as I remember, the task was, given an image (64x64x1) with a single white pixel, regress 2 outputs to determine the x, y coordinate yes? 

If so, I believe the issue you are facing is that it regressed the mean coordinates or something similar and is unable to improve from this local optima?

**Comment by vfdev-5** [comment]
> the task was, given an image (64x64x1) with a single white pixel, regress 2 outputs to determine the x, y coordinate yes?

@titu1994 correct.

>  If  so, I believe the issue you are facing is that it regressed the mean  coordinates or something similar and is unable to improve from this  local optima?

Looks like that

**Comment by titu1994** [comment]
> Funny thing is that classical network can learn this task as well as they stated.

Interesting. I haven't tried implementing it yet so I couldn't say really.

**Comment by vfdev-5** [comment]
Okay, thanks anyway. If you want to take a look at my implementation [here](https://github.com/vfdev-5/CoordConvExperiments).

Close the issue as it is not really one
